import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Fotter";
import { Inter } from "next/font/google";
const inter = Inter({subsets:["latin"]})
import StoreProvider from "@/provider/storeProvider";
import AuthProvider from "@/provider/authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} antialiased bg-background text-foreground`}
      >
        <StoreProvider>
         <AuthProvider>

          <Header></Header>
          {children}
          <Footer></Footer>
    
         </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
