import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Fotter";
import { Inter } from "next/font/google";
const inter = Inter({subsets:["latin"]})
import StoreProvider from "@/provider/storeProvider";
import AuthProvider from "@/provider/authProvider";
import { Toaster } from "@/components/ui/sonner"
import { toast } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className} antialiased bg-background text-foreground`}
      >
        <StoreProvider>
         <AuthProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
         <Toaster
              toastOptions={{
                classNames: {
                  toast: "bg-white text-black border border-gray-300 shadow-md rounded-lg",
                  title: "font-semibold text-lg",
                  description: "text-sm text-gray-600",
                  actionButton: "bg-white text-white hover:bg-blue-600",
                  cancelButton: "text-gray-500 hover:text-black",
                },
              }}
            />
         </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
